// neon/baseline.sql is the schema snapshot an empty database starts from
// before neon/migrations/*.sql are applied incrementally. This module builds
// that file from a schema-only pg_dump and reads the version marker back.
export const NEON_MIGRATION_FILE_PATTERN = /^(\d{14})_[\w-]+\.sql$/;

const VERSION_PATTERN = /^\d{14}$/;
const THROUGH_MARKER = "-- baseline-through:";
const MARKER_SEARCH_LINES = 20;

// pg_dump 17.6+ wraps plain dumps in psql-only meta-commands that a driver
// cannot execute.
const PSQL_META_COMMAND = /^\\(?:un)?restrict\b/;
// transaction_timeout exists only on Postgres 17+; the rest of the dump is
// version-neutral, so drop the one setting that would fail on 16.
const PG17_ONLY_SETTING = /^SET transaction_timeout\b/;

const ROLE_PROLOGUE = `-- Roles referenced by row-level-security policies below. Neon and Supabase
-- create them out of band; a plain Postgres needs them to exist first.
do $roles$
declare
  role_name text;
begin
  foreach role_name in array array['service_role', 'supabase_auth_admin'] loop
    if not exists (
      select 1 from pg_catalog.pg_roles where rolname = role_name
    ) then
      execute format('create role %I nologin', role_name);
    end if;
  end loop;
end
$roles$;`;

export function migrationVersion(fileName: string): string | null {
  return NEON_MIGRATION_FILE_PATTERN.exec(fileName)?.[1] ?? null;
}

export function latestMigrationVersion(
  fileNames: readonly string[]
): string | null {
  let latest: string | null = null;
  for (const fileName of fileNames) {
    const version = migrationVersion(fileName);
    if (version && (latest === null || Number(version) > Number(latest))) {
      latest = version;
    }
  }
  return latest;
}

export function parseBaselineThroughVersion(
  baselineSql: string
): string | null {
  for (const line of baselineSql.split("\n").slice(0, MARKER_SEARCH_LINES)) {
    if (!line.startsWith(THROUGH_MARKER)) {
      continue;
    }
    const version = line.slice(THROUGH_MARKER.length).trim();
    return VERSION_PATTERN.test(version) ? version : null;
  }
  return null;
}

export function buildNeonBaselineSql(
  rawDump: string,
  throughVersion: string
): string {
  if (!VERSION_PATTERN.test(throughVersion)) {
    throw new Error(`invalid baseline version: ${throughVersion}`);
  }
  if (!rawDump.includes("PostgreSQL database dump")) {
    throw new Error("input does not look like a plain-format pg_dump");
  }

  const body = rawDump
    .split("\n")
    .filter(
      (line) => !(PSQL_META_COMMAND.test(line) || PG17_ONLY_SETTING.test(line))
    )
    .join("\n")
    .trim();

  return [
    "-- Mogplex schema baseline for fresh databases.",
    "--",
    "-- Generated by scripts/build-neon-baseline.ts from a schema-only pg_dump of",
    "-- a database with every file in neon/migrations/ applied.",
    "-- scripts/apply-neon-migrations.ts runs this once on an empty database, then",
    "-- records every migration up to the version below as applied.",
    "-- Do not edit by hand; see neon/README.md to regenerate.",
    `${THROUGH_MARKER} ${throughVersion}`,
    "",
    ROLE_PROLOGUE,
    "",
    body,
    "",
  ].join("\n");
}
