-- better-auth tables move from text ids to uuid (every id is generated by
-- crypto.randomUUID via advanced.database.generateId), so profiles can FK
-- onto "user" directly. profiles.auth_user_id then references the better-auth
-- "user" table instead of the Supabase-era auth.users shim: better-auth owns
-- identity on Neon and the user-create hook provisions profiles for new
-- sign-ups. FK semantics match the original Supabase constraint
-- (unique + on delete set null). The data copy preserves Supabase auth uids
-- as better-auth "user" ids, so migrated profiles satisfy this unchanged.

alter table "session" drop constraint "session_userId_fkey";
alter table "account" drop constraint "account_userId_fkey";
alter table "ssoProvider" drop constraint "ssoProvider_userId_fkey";

alter table "user" alter column "id" type uuid using "id"::uuid;
alter table "session" alter column "userId" type uuid using "userId"::uuid;
alter table "account" alter column "userId" type uuid using "userId"::uuid;
alter table "ssoProvider" alter column "userId" type uuid using "userId"::uuid;

alter table "session"
  add constraint "session_userId_fkey"
  foreign key ("userId") references "user"("id") on delete cascade;
alter table "account"
  add constraint "account_userId_fkey"
  foreign key ("userId") references "user"("id") on delete cascade;
alter table "ssoProvider"
  add constraint "ssoProvider_userId_fkey"
  foreign key ("userId") references "user"("id") on delete cascade;

alter table profiles
  drop constraint if exists profiles_auth_user_id_fkey;

alter table profiles
  add constraint profiles_auth_user_id_fkey
  foreign key (auth_user_id) references "user"("id") on delete set null;
