export const TRIGGER_TASK_IDS = {
  automationJob: "execute-automation-job",
  externalAgentRun: "execute-external-agent-run",
  repoSnapshotBuild: "build-repo-snapshot",
  sandboxReaper: "sandbox-reaper",
  syncModels: "sync-models",
  sandboxAutoPause: "sandbox-auto-pause",
  sandboxBaselineSnapshotReaper: "reap-baseline-snapshots",
  sandboxReadinessReconciliation: "reconcile-sandbox-readiness",
  sandboxBillingReconciliation: "reconcile-sandbox-billing",
  vercelLinkReconciliation: "reconcile-vercel-links",
  aiCallCostReconciliation: "reconcile-ai-call-costs",
  annualIncludedUsageGrant: "grant-annual-included-usage",
  capacityAnnualIncludedUsageGrant: "grant-capacity-annual-included-usage",
  aiSpendDivergenceCheck: "check-ai-spend-divergence",
  zombieRowReaper: "zombie-row-reaper",
  slackEventHandler: "handle-slack-event",
  slackToolExecutionRetention: "retain-slack-tool-executions",
  workflowSchedule: "dispatch-workflow-schedule",
} as const;
