// Our little alien friend 👾, rasterized from the Mogplex mascot SVG at
// 22×18. Each "X" is solid, each "." is empty. Scaled up at render time to
// fit the hero; the swirl fills solid cells, the rest is background.
export const ALIEN_MASK: readonly string[] = [
  "....X..........X......",
  "....X..........X......",
  "...XXX........XXX.....",
  "....XXXXXXXXXXXXXX....",
  "...XXXXXXXXXXXXXXXX...",
  "..XXXXXXXXXXXXXXXXXX..",
  ".XX.XXX.XXXXXX.XXX.XX.",
  ".XX.XXX.XXXXXX.XXX.XX.",
  "XXXXXXXXXXXXXXXXXXXXXX",
  "XX.XXXXXXXXXXXXXXXX.XX",
  "XX..XXXXXXXXXXXXXX..XX",
  "...XXXXXXXXXXXXXXXX...",
  "....XXXXXXXXXXXXXX....",
  ".....XXXX....XXXX.....",
  ".....XXX......XXX.....",
  "....XXX........XXX....",
  "...XX............XX...",
  "..XX..............XX..",
] as const;

// Background swirl content — raw agent transcripts. Tool calls, inner
// thought traces, multi-agent chatter, hallucinated roadmaps, rewound
// plans, half-finished completions. The more unhinged the density the
// better the spiral reads.
const LINES = [
  "agent.think: the user wants a quieter console, not a quieter agent",
  '[tool_use] Bash("git bisect start HEAD HEAD~40") → started',
  '[tool_use] Read("hooks/use-sessions.ts", offset=240, limit=80)',
  "reflection: i keep drafting the fix before i understand the bug",
  "planner → coder: split PR, keep migration separate, land schema first",
  "coder → planner: understood. rewriting diff without the rename.",
  "subagent(explore) dispatched: map all call sites of launchSandbox()",
  "subagent(explore) returned 37 hits across 12 files (0.8s)",
  "hypothesis: race between useSandboxSync and sandbox.stop on unmount",
  "evidence: PTY transport emits 'close' before store marks stopped",
  "proposal: introduce transient 'stopping' state; block restart spam",
  "scoring candidates: safety 0.92 · blast_radius 0.14 · reversible ✓",
  '[tool_use] Edit(file_path="lib/sandbox/client.ts", …)',
  "self_critique: that catch block swallows the error i care about",
  "rewriting with narrower try; surfacing RuntimeError to observability",
  '[tool_use] Grep("createSandboxForRepo", type="ts") → 6 matches',
  "memory.save: user prefers flat UI — no backdrop-blur, no stat cards",
  "memory.hit: user confirmed single bundled PR over many small ones",
  "long_horizon_goal: make the workspace feel like a workbench, not a shell",
  "value_estimate(refactor_auth): 0.71 · effort 2d · risk medium",
  "dream(idle): a repo that narrates its own diff out loud",
  "dream(idle): agents that argue, then agree, then ship",
  "dream(idle): a sandbox that remembers the last good state",
  "dream(idle): panes that rearrange themselves around your attention",
  '[tool_use] Agent(subagent_type="debugger", prompt="track down reaper false-positive")',
  "debugger: reaper killed sandbox-7f3a9c while agent was mid-stream",
  "debugger: last_active_at not bumped by SSE heartbeats — root cause",
  "patch: touch last_active_at on every assistant token (throttled 1s)",
  "running: pnpm typecheck · pnpm lint · pnpm test:unit (in parallel)",
  "typecheck ✓  lint ✓  test:unit 127/127 ✓  build 23.4s",
  "trigger.dev task.succeeded in 4m12s (2,147,483 tokens billed)",
  "flow(step 3/7): waiting on human review — reviewer@mogplex.dev",
  "flow(step 4/7): approved — continuing.",
  "flow(step 5/7): running migration 20260416_profiles.sql",
  'observability.emit: activation="workspace_opened" source="cta"',
  "[meta] 2 agents, 7 tools, 14 memories in scope",
  "speculative_decode: branched on ambiguity, pruned 3 of 4 paths",
  "agent.yield: returning control to the orchestrator",
  "agent.resume: rehydrating pane tree · 4 panes · active=editor",
  'rewrite: "fix" → "surface the error the user will actually see"',
  "tool_router: Bash denied (dangerous), rerouted to Sandbox.exec",
  "confidence drops below 0.6 — asking the user instead of guessing",
  "question → user: should this ship behind a flag or straight to main?",
  "user → agent: straight to main. i'll revert if it regresses.",
  "agent.internalize: ship fast, revert faster, own the undo",
  "/imagine a terminal that finishes your sentence kindly",
  "/imagine a diff that writes its own release notes",
  "/imagine a workspace that wakes up where you left it",
  "/imagine an agent whose first tool is listening",
  "/imagine a build that fails in a useful direction",
  "/imagine a runtime that dreams of its own replacement",
  "ok — shipping. — mogplex",
];

export const MOGPLEX_SWIRL_TEXT: string = LINES.join("\n");
