/**
 * Worktree seed data for the Control surface.
 *
 * Extracted from seed.ts for module size compliance.
 * See seed.ts for the primary documentation.
 */

import type { Worktree } from "./types";

export function seedWorktrees(): Worktree[] {
  return [
    {
      id: "wt-a",
      mission: "MSN-241",
      ws: "ws-atlas",
      repo: "repo-atlas-workers",
      agent: "forge-1",
      harness: "claude-code",
      branch: "agent/atlas/cache-layer",
      task: "Add read-through cache for pricing lookups",
      action: "editing src/cache/redis.ts",
      state: "implementing",
      elapsed: "6m 12s",
      files: 9,
      ahead: 4,
      behind: 0,
      checks: "12/14",
      cost: 4.2,
      ctx: 62,
      sandbox: "container-med",
      risk: "medium",
      preview: "none",
      warn: "Touches 3 files also held by forge-2",
    },
    {
      id: "wt-b",
      mission: "MSN-241",
      ws: "ws-atlas",
      repo: "repo-atlas-api",
      agent: "forge-2",
      harness: "codex-cli",
      branch: "agent/atlas/query-batching",
      task: "Batch N+1 pricing queries at the resolver",
      action: "awaiting merge approval",
      state: "approval",
      elapsed: "11m 04s",
      files: 6,
      ahead: 3,
      behind: 0,
      checks: "14/14",
      cost: 5.9,
      ctx: 44,
      sandbox: "container-med",
      risk: "medium",
      preview: "preview-7f3 live",
      warn: "Touches 3 files also held by forge-1",
    },
    {
      id: "wt-c",
      mission: "MSN-241",
      ws: "ws-atlas",
      repo: "repo-atlas-api",
      agent: "forge-3",
      harness: "claude-code",
      branch: "agent/atlas/index-tuning",
      task: "Tune composite index on price_book",
      action: "run failed - pg container OOM",
      state: "failed",
      elapsed: "3m 41s",
      files: 2,
      ahead: 1,
      behind: 0,
      checks: "4/14",
      cost: 1.1,
      ctx: 19,
      sandbox: "container-med",
      risk: "low",
      preview: "none",
      warn: "Sandbox exceeded 2 GB memory limit",
    },
    {
      id: "wt-d",
      mission: "MSN-241",
      ws: "ws-atlas",
      repo: "repo-atlas-api",
      agent: "forge-4",
      harness: "aider",
      branch: "agent/atlas/edge-cache",
      task: "Cache pricing responses at the edge",
      action: "blocked - rebase conflict with main",
      state: "blocked",
      elapsed: "18m 30s",
      files: 4,
      ahead: 2,
      behind: 7,
      checks: "-",
      cost: 2.4,
      ctx: 51,
      sandbox: "container-sm",
      risk: "high",
      preview: "none",
      warn: "Conflict in src/pricing/resolver.ts",
    },
    {
      id: "wt-e",
      mission: "MSN-238",
      ws: "ws-atlas",
      repo: "repo-atlas-api",
      agent: "forge-0",
      harness: "claude-code",
      branch: "agent/atlas/telemetry-baseline",
      task: "Capture p95 baseline telemetry",
      action: "merged into main, worktree archived",
      state: "archived",
      elapsed: "-",
      files: 5,
      ahead: 0,
      behind: 0,
      checks: "14/14",
      cost: 3.8,
      ctx: 0,
      sandbox: "container-sm",
      risk: "none",
      preview: "none",
      warn: "",
    },
  ];
}
