import { getOAuthToken } from "@/lib/oauth-tokens";
import {
  normalizeEnvSyncMode,
  normalizeEnvVars,
  normalizeRootDirectory,
  resolveSandboxPath,
} from "@/lib/repo-settings";
import type { EnvSyncMode, RepoEnvVars } from "@/lib/repo-settings";
import type { Sandbox } from "@vercel/sandbox";

export type VercelEnvVar = {
  id?: string;
  key: string;
  value?: string;
  target?: string[];
  type?: "encrypted" | "plain" | "secret" | "system";
  configurationId?: string | null;
  createdAt?: number;
  updatedAt?: number;
};

const DEFAULT_TARGET_PRIORITY = ["preview", "development"] as const;
const ENV_SYNC_LOG_PREFIX = "[vercel/env-sync]";
const GENERATED_ENV_FILE_HEADER =
  "# Generated by Mogplex for linked Vercel bootstrap.";
const GENERATED_ENV_FILE_RELATIVE_PATH = ".vercel/.env.preview.local";
const GENERATED_PROJECT_FILE_RELATIVE_PATH = ".vercel/project.json";
const GENERATED_ROOT_ENV_FILE_RELATIVE_PATH = ".env.local";
const GENERATED_MANIFEST_RELATIVE_PATH = ".mogplex/vercel-link-manifest.json";

type RepoSandboxEnvRepo = {
  sandbox_env_vars?: unknown;
  env_sync_mode?: unknown;
  vercel_project_id?: string | null;
  vercel_team_id?: string | null;
};

type SandboxFileAccess = Pick<
  Sandbox,
  "readFileToBuffer" | "runCommand" | "writeFiles"
>;

export type LinkedVercelProject = {
  projectId: string;
  teamId?: string | null;
};

export type RepoSandboxEnvResolution = {
  envVars: RepoEnvVars;
  sync: {
    mode: EnvSyncMode;
    source: "manual" | "vercel-project" | "manual+vercel-project";
    warning: string | null;
  };
};

type PreparedVercelLinkManifest = {
  version: 1;
  files: string[];
};

export type PrepareSandboxVercelLinkResult = {
  applied: boolean;
  warning: string | null;
  generatedFiles: string[];
};

function escapeShell(value: string) {
  return value.replace(/'/g, String.raw`'\''`);
}

function buildShellCommand(command: string, rootDirectory?: string | null) {
  const normalizedRoot = normalizeRootDirectory(rootDirectory);
  if (!normalizedRoot) return command;
  return `cd '${escapeShell(normalizedRoot)}' && ${command}`;
}

function buildGeneratedEnvFile(envVars: RepoEnvVars) {
  const lines = Object.entries(envVars)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${JSON.stringify(value)}`);

  return `${GENERATED_ENV_FILE_HEADER}\n${lines.join("\n")}${lines.length > 0 ? "\n" : ""}`;
}

function buildLinkedProjectFile(project: LinkedVercelProject) {
  const payload: { projectId: string; orgId?: string } = {
    projectId: project.projectId,
  };
  if (project.teamId && project.teamId !== "personal") {
    payload.orgId = project.teamId;
  }
  return `${JSON.stringify(payload, null, 2)}\n`;
}

function buildPreparedLinkManifest(files: string[]): string {
  const payload: PreparedVercelLinkManifest = {
    version: 1,
    files,
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

async function readSandboxTextFile(sandbox: SandboxFileAccess, path: string) {
  try {
    const buffer = await sandbox.readFileToBuffer({ path });
    return buffer ? buffer.toString("utf-8") : null;
  } catch {
    return null;
  }
}

function isGeneratedEnvFile(text: string | null) {
  return Boolean(text?.startsWith(GENERATED_ENV_FILE_HEADER));
}

function projectFileMatches(text: string | null, project: LinkedVercelProject) {
  if (!text) return false;

  try {
    const parsed = JSON.parse(text) as { projectId?: string; orgId?: string };
    const expectedOrgId =
      project.teamId && project.teamId !== "personal"
        ? project.teamId
        : undefined;
    return (
      parsed.projectId === project.projectId && parsed.orgId === expectedOrgId
    );
  } catch {
    return false;
  }
}

function resolveGeneratedLinkPaths(rootDirectory?: string | null) {
  return {
    projectFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_PROJECT_FILE_RELATIVE_PATH
    ),
    previewEnvFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_ENV_FILE_RELATIVE_PATH
    ),
    rootEnvFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_ROOT_ENV_FILE_RELATIVE_PATH
    ),
    manifestFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_MANIFEST_RELATIVE_PATH
    ),
  };
}

function parsePreparedLinkManifest(text: string): PreparedVercelLinkManifest {
  const parsed = JSON.parse(text) as { version?: number; files?: unknown };
  if (
    parsed.version !== 1 ||
    !Array.isArray(parsed.files) ||
    parsed.files.some((file) => typeof file !== "string")
  ) {
    throw new Error("Invalid Mogplex Vercel link manifest");
  }
  return {
    version: 1,
    files: parsed.files,
  };
}

function buildProjectEnvUrl(opts: {
  vercelProjectId: string;
  vercelTeamId?: string | null;
  decrypt?: boolean;
}) {
  const base = `https://api.vercel.com/v10/projects/${opts.vercelProjectId}/env`;
  const params = new URLSearchParams();
  if (opts.vercelTeamId && opts.vercelTeamId !== "personal") {
    params.set("teamId", opts.vercelTeamId);
  }
  if (opts.decrypt) {
    params.set("decrypt", "true");
  }
  const query = params.toString();
  return query ? `${base}?${query}` : base;
}

async function getUserVercelToken(userId: string) {
  return getOAuthToken(userId, "vercel");
}

function resolveSyncSource(
  manualEnvVars: RepoEnvVars,
  vercelEnvVars: RepoEnvVars
): RepoSandboxEnvResolution["sync"]["source"] {
  const hasManual = Object.keys(manualEnvVars).length > 0;
  const hasVercel = Object.keys(vercelEnvVars).length > 0;
  if (hasManual && hasVercel) return "manual+vercel-project";
  if (hasVercel) return "vercel-project";
  return "manual";
}

function warnAndReturnFallback(
  mode: EnvSyncMode,
  manualEnvVars: RepoEnvVars,
  warning: string,
  error?: unknown
): RepoSandboxEnvResolution {
  if (error) {
    console.warn(ENV_SYNC_LOG_PREFIX, warning, error);
  } else {
    console.warn(ENV_SYNC_LOG_PREFIX, warning);
  }

  return {
    envVars: manualEnvVars,
    sync: {
      mode,
      source: "manual",
      warning,
    },
  };
}

export async function fetchVercelProjectEnvEntries(opts: {
  vercelToken: string;
  vercelProjectId: string;
  vercelTeamId?: string | null;
  decrypt?: boolean;
}): Promise<VercelEnvVar[]> {
  const res = await fetch(
    buildProjectEnvUrl({
      vercelProjectId: opts.vercelProjectId,
      vercelTeamId: opts.vercelTeamId,
      decrypt: opts.decrypt,
    }),
    {
      headers: {
        Authorization: `Bearer ${opts.vercelToken}`,
        "Content-Type": "application/json",
      },
      cache: "no-store",
    }
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Vercel API (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { envs?: VercelEnvVar[] };
  return data.envs ?? [];
}

export function flattenVercelProjectEnvVars(
  envs: VercelEnvVar[],
  targetPriority: readonly string[] = DEFAULT_TARGET_PRIORITY
): RepoEnvVars {
  const result: RepoEnvVars = {};

  for (const target of targetPriority) {
    for (const env of envs) {
      if (!env.key || env.value == null) continue;
      const envTargets = env.target ?? [];
      if (!envTargets.includes(target)) continue;
      if (!(env.key in result)) {
        result[env.key] = env.value;
      }
    }
  }

  return result;
}

export function mergeRepoSandboxEnvVars(
  vercelEnvVars: RepoEnvVars,
  manualEnvVars: RepoEnvVars
): RepoEnvVars {
  return {
    ...vercelEnvVars,
    ...manualEnvVars,
  };
}

export function getRepoLinkedVercelProject(
  repo: RepoSandboxEnvRepo
): LinkedVercelProject | null {
  if (
    normalizeEnvSyncMode(repo.env_sync_mode) !== "vercel-project" ||
    !repo.vercel_project_id
  ) {
    return null;
  }

  return {
    projectId: repo.vercel_project_id,
    teamId: repo.vercel_team_id,
  };
}

export async function resolveRepoSandboxEnv(opts: {
  repo: RepoSandboxEnvRepo;
  userId: string;
}): Promise<RepoSandboxEnvResolution> {
  const mode = normalizeEnvSyncMode(opts.repo.env_sync_mode);
  const manualEnvVars = normalizeEnvVars(opts.repo.sandbox_env_vars);

  if (mode !== "vercel-project") {
    return {
      envVars: manualEnvVars,
      sync: {
        mode,
        source: "manual",
        warning: null,
      },
    };
  }

  if (!opts.repo.vercel_project_id) {
    return warnAndReturnFallback(
      mode,
      manualEnvVars,
      "Linked Vercel project env sync skipped: no Vercel project is linked; using manual env vars only."
    );
  }

  let vercelToken: string | null;
  try {
    vercelToken = await getUserVercelToken(opts.userId);
  } catch (error) {
    return warnAndReturnFallback(
      mode,
      manualEnvVars,
      "Linked Vercel project env sync skipped: failed to load the connected Vercel token; using manual env vars only.",
      error
    );
  }

  if (!vercelToken) {
    return warnAndReturnFallback(
      mode,
      manualEnvVars,
      "Linked Vercel project env sync skipped: reconnect Vercel to restore project env access; using manual env vars only."
    );
  }

  try {
    const vercelEntries = await fetchVercelProjectEnvEntries({
      vercelToken,
      vercelProjectId: opts.repo.vercel_project_id,
      vercelTeamId: opts.repo.vercel_team_id,
      decrypt: true,
    });
    const vercelEnvVars = flattenVercelProjectEnvVars(vercelEntries);

    return {
      envVars: mergeRepoSandboxEnvVars(vercelEnvVars, manualEnvVars),
      sync: {
        mode,
        source: resolveSyncSource(manualEnvVars, vercelEnvVars),
        warning: null,
      },
    };
  } catch (error) {
    return warnAndReturnFallback(
      mode,
      manualEnvVars,
      "Linked Vercel project env sync failed; using manual env vars only.",
      error
    );
  }
}

export async function prepareSandboxVercelLink(
  sandbox: SandboxFileAccess,
  opts: {
    rootDirectory?: string | null;
    envSyncMode?: unknown;
    envVars?: unknown;
    linkedProject?: LinkedVercelProject | null;
  }
): Promise<PrepareSandboxVercelLinkResult> {
  const mode = normalizeEnvSyncMode(opts.envSyncMode);
  if (mode !== "vercel-project" || !opts.linkedProject?.projectId) {
    return {
      applied: false,
      warning: null,
      generatedFiles: [],
    };
  }

  const envVars = normalizeEnvVars(opts.envVars);
  const paths = resolveGeneratedLinkPaths(opts.rootDirectory);
  const warnings: string[] = [];

  try {
    const [existingProjectFile, existingPreviewEnvFile, existingRootEnvFile] =
      await Promise.all([
        readSandboxTextFile(sandbox, paths.projectFile),
        readSandboxTextFile(sandbox, paths.previewEnvFile),
        readSandboxTextFile(sandbox, paths.rootEnvFile),
      ]);

    const writes: Array<{ path: string; content: Buffer }> = [];
    const generatedFiles: string[] = [];
    const linkedProjectFile = buildLinkedProjectFile(opts.linkedProject);
    const generatedEnvFile = buildGeneratedEnvFile(envVars);

    if (!existingProjectFile) {
      writes.push({
        path: paths.projectFile,
        content: Buffer.from(linkedProjectFile),
      });
      generatedFiles.push(paths.projectFile);
    } else if (!projectFileMatches(existingProjectFile, opts.linkedProject)) {
      warnings.push(
        "Linked Vercel project bootstrap skipped overwriting an existing .vercel/project.json that points at a different project."
      );
    }

    if (!existingPreviewEnvFile || isGeneratedEnvFile(existingPreviewEnvFile)) {
      writes.push({
        path: paths.previewEnvFile,
        content: Buffer.from(generatedEnvFile),
      });
      generatedFiles.push(paths.previewEnvFile);
    }

    if (!existingRootEnvFile || isGeneratedEnvFile(existingRootEnvFile)) {
      writes.push({
        path: paths.rootEnvFile,
        content: Buffer.from(generatedEnvFile),
      });
      generatedFiles.push(paths.rootEnvFile);
    }

    if (writes.length === 0) {
      return {
        applied: false,
        warning: warnings.length > 0 ? warnings.join(" ") : null,
        generatedFiles: [],
      };
    }

    const mkdir = await sandbox.runCommand({
      cmd: "sh",
      args: [
        "-lc",
        buildShellCommand("mkdir -p .vercel .mogplex", opts.rootDirectory),
      ],
    });
    if (mkdir.exitCode !== 0) {
      throw new Error("Failed to create Vercel bootstrap directories");
    }

    writes.push({
      path: paths.manifestFile,
      content: Buffer.from(buildPreparedLinkManifest(generatedFiles)),
    });

    await sandbox.writeFiles(writes);

    return {
      applied: true,
      warning: warnings.length > 0 ? warnings.join(" ") : null,
      generatedFiles,
    };
  } catch (error) {
    const warning =
      "Linked Vercel project bootstrap could not materialize sandbox linkage; continuing with process env injection only.";
    console.warn(ENV_SYNC_LOG_PREFIX, warning, error);
    return {
      applied: false,
      warning,
      generatedFiles: [],
    };
  }
}

export async function cleanupPreparedSandboxVercelLink(
  sandbox: SandboxFileAccess,
  opts: {
    rootDirectory?: string | null;
  }
): Promise<{ removedFiles: string[] }> {
  const { manifestFile } = resolveGeneratedLinkPaths(opts.rootDirectory);
  const manifestText = await readSandboxTextFile(sandbox, manifestFile);
  if (!manifestText) {
    return { removedFiles: [] };
  }

  const manifest = parsePreparedLinkManifest(manifestText);
  const filesToRemove = [...manifest.files, manifestFile];
  if (filesToRemove.length === 0) {
    return { removedFiles: [] };
  }

  const remove = await sandbox.runCommand({
    cmd: "sh",
    args: [
      "-lc",
      `rm -f ${filesToRemove.map((path) => `'${escapeShell(path)}'`).join(" ")}`,
    ],
  });

  if (remove.exitCode !== 0) {
    throw new Error(
      "Failed to remove generated Vercel bootstrap files before snapshotting"
    );
  }

  return {
    removedFiles: manifest.files,
  };
}
