import {
  normalizeEnvVars,
  normalizeRootDirectory,
  resolveEffectiveEnvSyncMode,
  resolveSandboxPath,
} from "@/lib/repo-settings";
import type { RepoEnvVars } from "@/lib/repo-settings";
import type { Sandbox } from "@vercel/sandbox";
import type { LinkedVercelProject } from "./env-vars";

const ENV_SYNC_LOG_PREFIX = "[vercel/env-sync]";
const GENERATED_ENV_FILE_HEADER =
  "# Generated by Mogplex for linked Vercel bootstrap.";
const GENERATED_ENV_FILE_RELATIVE_PATH = ".vercel/.env.preview.local";
const GENERATED_PROJECT_FILE_RELATIVE_PATH = ".vercel/project.json";
const GENERATED_ROOT_ENV_FILE_RELATIVE_PATH = ".env.local";
const GENERATED_MANIFEST_RELATIVE_PATH = ".mogplex/vercel-link-manifest.json";

type SandboxFileAccess = Pick<
  Sandbox,
  "readFileToBuffer" | "runCommand" | "writeFiles"
>;

type PreparedVercelLinkManifest = {
  version: 1;
  files: string[];
};

export type PrepareSandboxVercelLinkResult = {
  applied: boolean;
  warning: string | null;
  generatedFiles: string[];
};

function escapeShell(value: string) {
  return value.replace(/'/g, String.raw`'\''`);
}

function buildShellCommand(command: string, rootDirectory?: string | null) {
  const normalizedRoot = normalizeRootDirectory(rootDirectory);
  if (!normalizedRoot) return command;
  return `cd '${escapeShell(normalizedRoot)}' && ${command}`;
}

function buildGeneratedEnvFile(envVars: RepoEnvVars) {
  const lines = Object.entries(envVars)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${JSON.stringify(value)}`);

  return `${GENERATED_ENV_FILE_HEADER}\n${lines.join("\n")}${lines.length > 0 ? "\n" : ""}`;
}

function buildLinkedProjectFile(project: LinkedVercelProject) {
  const payload: { projectId: string; orgId?: string } = {
    projectId: project.projectId,
  };
  if (project.teamId && project.teamId !== "personal") {
    payload.orgId = project.teamId;
  }
  return `${JSON.stringify(payload, null, 2)}\n`;
}

function buildPreparedLinkManifest(files: string[]): string {
  const payload: PreparedVercelLinkManifest = {
    version: 1,
    files,
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

async function readSandboxTextFile(sandbox: SandboxFileAccess, path: string) {
  try {
    const buffer = await sandbox.readFileToBuffer({ path });
    return buffer ? buffer.toString("utf-8") : null;
  } catch {
    return null;
  }
}

function isGeneratedEnvFile(text: string | null) {
  return Boolean(text?.startsWith(GENERATED_ENV_FILE_HEADER));
}

function projectFileMatches(text: string | null, project: LinkedVercelProject) {
  if (!text) return false;

  try {
    const parsed = JSON.parse(text) as { projectId?: string; orgId?: string };
    const expectedOrgId =
      project.teamId && project.teamId !== "personal"
        ? project.teamId
        : undefined;
    return (
      parsed.projectId === project.projectId && parsed.orgId === expectedOrgId
    );
  } catch {
    return false;
  }
}

function resolveGeneratedLinkPaths(rootDirectory?: string | null) {
  return {
    projectFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_PROJECT_FILE_RELATIVE_PATH
    ),
    previewEnvFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_ENV_FILE_RELATIVE_PATH
    ),
    rootEnvFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_ROOT_ENV_FILE_RELATIVE_PATH
    ),
    manifestFile: resolveSandboxPath(
      rootDirectory,
      GENERATED_MANIFEST_RELATIVE_PATH
    ),
  };
}

function parsePreparedLinkManifest(text: string): PreparedVercelLinkManifest {
  const parsed = JSON.parse(text) as { version?: number; files?: unknown };
  if (
    parsed.version !== 1 ||
    !Array.isArray(parsed.files) ||
    parsed.files.some((file) => typeof file !== "string")
  ) {
    throw new Error("Invalid Mogplex Vercel link manifest");
  }
  return {
    version: 1,
    files: parsed.files,
  };
}

export async function prepareSandboxVercelLink(
  sandbox: SandboxFileAccess,
  opts: {
    rootDirectory?: string | null;
    envSyncMode?: unknown;
    envVars?: unknown;
    linkedProject?: LinkedVercelProject | null;
  }
): Promise<PrepareSandboxVercelLinkResult> {
  const mode = resolveEffectiveEnvSyncMode(opts.envSyncMode);
  if (mode !== "vercel-project" || !opts.linkedProject?.projectId) {
    return {
      applied: false,
      warning: null,
      generatedFiles: [],
    };
  }

  const envVars = normalizeEnvVars(opts.envVars);
  const paths = resolveGeneratedLinkPaths(opts.rootDirectory);
  const warnings: string[] = [];

  try {
    const [existingProjectFile, existingPreviewEnvFile, existingRootEnvFile] =
      await Promise.all([
        readSandboxTextFile(sandbox, paths.projectFile),
        readSandboxTextFile(sandbox, paths.previewEnvFile),
        readSandboxTextFile(sandbox, paths.rootEnvFile),
      ]);

    const writes: Array<{ path: string; content: Buffer }> = [];
    const generatedFiles: string[] = [];
    const linkedProjectFile = buildLinkedProjectFile(opts.linkedProject);
    const generatedEnvFile = buildGeneratedEnvFile(envVars);

    if (!existingProjectFile) {
      writes.push({
        path: paths.projectFile,
        content: Buffer.from(linkedProjectFile),
      });
      generatedFiles.push(paths.projectFile);
    } else if (!projectFileMatches(existingProjectFile, opts.linkedProject)) {
      warnings.push(
        "Linked Vercel project bootstrap skipped overwriting an existing .vercel/project.json that points at a different project."
      );
    }

    if (!existingPreviewEnvFile || isGeneratedEnvFile(existingPreviewEnvFile)) {
      writes.push({
        path: paths.previewEnvFile,
        content: Buffer.from(generatedEnvFile),
      });
      generatedFiles.push(paths.previewEnvFile);
    }

    if (!existingRootEnvFile || isGeneratedEnvFile(existingRootEnvFile)) {
      writes.push({
        path: paths.rootEnvFile,
        content: Buffer.from(generatedEnvFile),
      });
      generatedFiles.push(paths.rootEnvFile);
    }

    if (writes.length === 0) {
      return {
        applied: false,
        warning: warnings.length > 0 ? warnings.join(" ") : null,
        generatedFiles: [],
      };
    }

    const mkdir = await sandbox.runCommand({
      cmd: "sh",
      args: [
        "-lc",
        buildShellCommand("mkdir -p .vercel .mogplex", opts.rootDirectory),
      ],
    });
    if (mkdir.exitCode !== 0) {
      throw new Error("Failed to create Vercel bootstrap directories");
    }

    writes.push({
      path: paths.manifestFile,
      content: Buffer.from(buildPreparedLinkManifest(generatedFiles)),
    });

    await sandbox.writeFiles(writes);

    return {
      applied: true,
      warning: warnings.length > 0 ? warnings.join(" ") : null,
      generatedFiles,
    };
  } catch (error) {
    const warning =
      "Linked Vercel project bootstrap could not materialize sandbox linkage; continuing with process env injection only.";
    console.warn(ENV_SYNC_LOG_PREFIX, warning, error);
    return {
      applied: false,
      warning,
      generatedFiles: [],
    };
  }
}

export async function cleanupPreparedSandboxVercelLink(
  sandbox: SandboxFileAccess,
  opts: {
    rootDirectory?: string | null;
  }
): Promise<{ removedFiles: string[] }> {
  const { manifestFile } = resolveGeneratedLinkPaths(opts.rootDirectory);
  const manifestText = await readSandboxTextFile(sandbox, manifestFile);
  if (!manifestText) {
    return { removedFiles: [] };
  }

  const manifest = parsePreparedLinkManifest(manifestText);
  const filesToRemove = [...manifest.files, manifestFile];
  if (filesToRemove.length === 0) {
    return { removedFiles: [] };
  }

  const remove = await sandbox.runCommand({
    cmd: "sh",
    args: [
      "-lc",
      `rm -f ${filesToRemove.map((path) => `'${escapeShell(path)}'`).join(" ")}`,
    ],
  });

  if (remove.exitCode !== 0) {
    throw new Error(
      "Failed to remove generated Vercel bootstrap files before snapshotting"
    );
  }

  return {
    removedFiles: manifest.files,
  };
}
