ALTER TABLE repos ADD COLUMN IF NOT EXISTS root_directory TEXT;
ALTER TABLE repos ADD COLUMN IF NOT EXISTS install_command TEXT;
ALTER TABLE repos ADD COLUMN IF NOT EXISTS dev_command TEXT;
ALTER TABLE repos ADD COLUMN IF NOT EXISTS dev_port INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE repos ADD COLUMN IF NOT EXISTS sandbox_timeout_ms INTEGER NOT NULL DEFAULT 600000;
ALTER TABLE repos ADD COLUMN IF NOT EXISTS sandbox_env_vars JSONB NOT NULL DEFAULT '{}'::jsonb;
