-- Seed ai_models with the app catalog
INSERT INTO ai_models (id, provider, name, context_length, is_available) VALUES
  ('minimax/minimax-m2.5',           'minimax',    'minimax-m2.5',                   205000,  true),
  ('sakana/fugu-ultra',              'sakana',     'Fugu Ultra',                    1000000,  true),
  ('anthropic/claude-fable-5',       'anthropic',  'claude-fable-5',                1000000,  true),
  ('anthropic/claude-opus-4.8',      'anthropic',  'claude-opus-4.8',               1000000,  true),
  ('anthropic/claude-sonnet-5',      'anthropic',  'claude-sonnet-5',               1000000,  true),
  ('anthropic/claude-sonnet-4.6',    'anthropic',  'claude-sonnet-4.6',             1000000,  true),
  ('anthropic/claude-haiku-4.5',     'anthropic',  'claude-haiku-4.5',               200000,  true),
  ('openai/gpt-5.4',                 'openai',     'gpt-5.4',                       1100000,  true),
  ('openai/gpt-5.3-codex',           'openai',     'gpt-5.3-codex',                  400000,  true),
  ('openai/gpt-5.2',                 'openai',     'gpt-5.2',                        400000,  true),
  ('openai/gpt-5.1-instant',         'openai',     'gpt-5.1-instant',                128000,  true),
  ('openai/gpt-5',                   'openai',     'gpt-5',                          400000,  true),
  ('openai/gpt-5-mini',              'openai',     'gpt-5-mini',                     400000,  true),
  ('openai/gpt-4.1-mini',            'openai',     'gpt-4.1-mini',                  1000000,  true),
  ('openai/gpt-oss-120b',            'openai',     'gpt-oss-120b',                   131000,  true),
  ('openai/gpt-oss-20b',             'openai',     'gpt-oss-20b',                    131000,  true),
  ('google/gemini-3.1-pro-preview',  'google',     'gemini-3.1-pro-preview',        1000000,  true),
  ('google/gemini-3.1-flash-lite',   'google',     'gemini-3.1-flash-lite-preview', 1000000,  true),
  ('google/gemini-3-flash',          'google',     'gemini-3-flash',                1000000,  true),
  ('google/gemini-3-pro-preview',    'google',     'gemini-3-pro-preview',          1000000,  true),
  ('google/gemini-2.5-flash',        'google',     'gemini-2.5-flash',              1000000,  true),
  ('google/gemini-2.5-flash-lite',   'google',     'gemini-2.5-flash-lite',         1000000,  true),
  ('xai/grok-4.1-non-reasoning',     'xai',        'grok-4.1-fast-non-reasoning',  2000000,  true),
  ('xai/grok-4.1-reasoning',         'xai',        'grok-4.1-fast-reasoning',      2000000,  true),
  ('xai/grok-code-fast-1',           'xai',        'grok-code-fast-1',              256000,  true),
  ('deepseek/deepseek-v3.2',         'deepseek',   'deepseek-v3.2',                 164000,  true),
  ('moonshotai/kimi-k2.5',           'moonshotai', 'kimi-k2.5',                     262000,  true),
  ('kwaipilot/kat-coder-pro-v1',     'kwaipilot',  'kat-coder-pro-v1',              256000,  true),
  ('zai/glm-5',                      'zai',        'glm-5',                         203000,  true)
ON CONFLICT (id) DO UPDATE SET
  provider = EXCLUDED.provider,
  name = EXCLUDED.name,
  context_length = EXCLUDED.context_length,
  is_available = EXCLUDED.is_available;
